//
//  Defaults.swift
//  Wheellog.iOS
//
//  Created by nathan retta on 1/16/24.
//

import Foundation

enum Defaults {
    case speakerMute
    case fanEnabled
    case fanQuietEnable
    case lightBrightness
    case wheelAlarm3
    case wheelAlarm3Enabled
    case wheelAlarm2
    case wheelAlarm2Enabled
    case wheelAlarm1
    case wheelAlarm1Enabled
    case wheelLimitedModeEnabled
    case wheelLimitedSpeed
    case nbLedColor1
    case nbLedColor2
    case nbLedColor3
    case nbLedColor4
    case brakeAssistantEnabled
    case useEng
    case appTheme
    case dayNightTheme
    case useBetterPercents
    case customPercents
    case cellVoltageTiltback
    case useMph
    case useFahrenheit
    case viewBlocksString
    case pwm
    case maxPwm
    case voltage
    case avgRiding
    case ridingTime
    case topSpeed
    case distance
    case total
    case usePipMode
    case pipBlock
    case notificationButtons
    case maxSpeed
    case currentOnDial
    case showPageGraph
    case showPageEvents
    case showPageTrips
    case connectionSound
    case noConnectionSound
    case useStopMusic
    case showUnknownDevices
    case beepOnSingleTap
    case beepOnVolumeUp
    case beepByWheel
    case customBeep
    case beepFile
    case mibandMode
    case useReconnect
    case useDetectBatteryOptimization
    case privatePolicyAccepted
    case yandexMetricaAccepted
    case autoLog
    case autoWatch
    case autoUploadEc
    case logLocationData
    case ecUserId
    case ecToken
    case ecGarage
    case useRawData
    case autoLogWhenMovingMore
    case continueThisDayLog
    case continueThisDayLogException
    case hornMode
    case garminConnectiqEnable
    case garminConnectiqUseBeta
    case mibandFixrsEnable
    case lastMac
    case useGps
    case useShortPwm
    case alarmsEnabled
    case disablePhoneVibrate
    case disablePhoneBeep
    case useWheelBeepForAlarm
    case alteredAlarms
    case alarm1Speed
    case alarm1Battery
    case alarm2Speed
    case alarm2Battery
    case alarm3Speed
    case alarm3Battery
    case alarmTemperature
    case rotationSpeed
    case rotationVoltage
    case rotationSet
    case powerFactor
    case alarmFactor1
    case alarmFactor2
    case alarmFactor3
    case warningSpeed
    case warningPwm
    case warningSpeedPeriod
    case alarmCurrent
    case alarmBattery
    case ledEnabled
    case drlEnabled
    case taillightEnabled
    case handleButtonDisabled
    case speakerVolume
    case beeperVolume
    case pedalsAdjustment
    case pedalSensivity
    case lightMode
    case strobeMode
    case ledMode
    case pedalsMode
    case rollAngle
    case rideMode
    case lockMode
    case transportMode
    case goHomeMode
    case fancierMode
    case alarmMode
    case wheelMaxSpeed
    case wheelKsAlarm1
    case wheelKsAlarm2
    case wheelKsAlarm3
    case ks18lScaler
    case useRatio
    case gwInMiles
    case gotwayVoltage
    case gotwayNegative
    case hwPwm
    case connectBeep
    case lightEnabled
    case profileName
    case batteryCapacity
    case chargingPower
    case iconConnection
    case iconLogging
    case iconWatch
    
    func res() -> String {
        switch self {
        case .speakerMute:
            return DefaultStrings.speakerMute
        case .fanEnabled:
            return DefaultStrings.fanEnabled
        case .fanQuietEnable:
            return DefaultStrings.fanQuietEnable
        case .lightBrightness:
            return DefaultStrings.lightBrightness
        case .wheelAlarm3:
            return DefaultStrings.wheelAlarm3
        case .wheelAlarm3Enabled:
            return DefaultStrings.wheelAlarm3Enabled
        case .wheelAlarm2:
            return DefaultStrings.wheelAlarm2
        case .wheelAlarm2Enabled:
            return DefaultStrings.wheelAlarm2Enabled
        case .wheelAlarm1:
            return DefaultStrings.wheelAlarm1
        case .wheelAlarm1Enabled:
            return DefaultStrings.wheelAlarm1Enabled
        case .wheelLimitedModeEnabled:
            return DefaultStrings.wheelLimitedModeEnabled
        case .wheelLimitedSpeed:
            return DefaultStrings.wheelLimitedSpeed
        case .nbLedColor1:
            return DefaultStrings.nbLedColor1
        case .nbLedColor2:
            return DefaultStrings.nbLedColor2
        case .nbLedColor3:
            return DefaultStrings.nbLedColor3
        case .nbLedColor4:
            return DefaultStrings.nbLedColor4
        case .brakeAssistantEnabled:
            return DefaultStrings.brakeAssistantEnabled
        case .useEng:
            return DefaultStrings.useEng
        case .appTheme:
            return DefaultStrings.appTheme
        case .dayNightTheme:
            return DefaultStrings.dayNightTheme
        case .useBetterPercents:
            return DefaultStrings.useBetterPercents
        case .customPercents:
            return DefaultStrings.customPercents
        case .cellVoltageTiltback:
            return DefaultStrings.cellVoltageTiltback
        case .useMph:
            return DefaultStrings.useMph
        case .useFahrenheit:
            return DefaultStrings.useFahrenheit
        case .viewBlocksString:
            return DefaultStrings.viewBlocksString
        case .pwm:
            return DefaultStrings.pwm
        case .maxPwm:
            return DefaultStrings.maxPwm
        case .voltage:
            return DefaultStrings.voltage
        case .avgRiding:
            return DefaultStrings.avgRiding
        case .ridingTime:
            return DefaultStrings.ridingTime
        case .topSpeed:
            return DefaultStrings.topSpeed
        case .distance:
            return DefaultStrings.distance
        case .total:
            return DefaultStrings.total
        case .usePipMode:
            return DefaultStrings.usePipMode
        case .pipBlock:
            return DefaultStrings.pipBlock
        case .notificationButtons:
            return DefaultStrings.notificationButtons
        case .maxSpeed:
            return DefaultStrings.maxSpeed
        case .currentOnDial:
            return DefaultStrings.currentOnDial
        case .showPageGraph:
            return DefaultStrings.showPageGraph
        case .showPageEvents:
            return DefaultStrings.showPageEvents
        case .showPageTrips:
            return DefaultStrings.showPageTrips
        case .connectionSound:
            return DefaultStrings.connectionSound
        case .noConnectionSound:
            return DefaultStrings.noConnectionSound
        case .useStopMusic:
            return DefaultStrings.useStopMusic
        case .showUnknownDevices:
            return DefaultStrings.showUnknownDevices
        case .beepOnSingleTap:
            return DefaultStrings.beepOnSingleTap
        case .beepOnVolumeUp:
            return DefaultStrings.beepOnVolumeUp
        case .beepByWheel:
            return DefaultStrings.beepByWheel
        case .customBeep:
            return DefaultStrings.customBeep
        case .beepFile:
            return DefaultStrings.beepFile
        case .mibandMode:
            return DefaultStrings.mibandMode
        case .useReconnect:
            return DefaultStrings.useReconnect
        case .useDetectBatteryOptimization:
            return DefaultStrings.useDetectBatteryOptimization
        case .privatePolicyAccepted:
            return DefaultStrings.privatePolicyAccepted
        case .yandexMetricaAccepted:
            return DefaultStrings.yandexMetricaAccepted
        case .autoLog:
            return DefaultStrings.autoLog
        case .autoWatch:
            return DefaultStrings.autoWatch
        case .autoUploadEc:
            return DefaultStrings.autoUploadEc
        case .logLocationData:
            return DefaultStrings.logLocationData
        case .ecUserId:
            return DefaultStrings.ecUserId
        case .ecToken:
            return DefaultStrings.ecToken
        case .ecGarage:
            return DefaultStrings.ecGarage
        case .useRawData:
            return DefaultStrings.useRawData
        case .autoLogWhenMovingMore:
            return DefaultStrings.autoLogWhenMovingMore
        case .continueThisDayLog:
            return DefaultStrings.continueThisDayLog
        case .continueThisDayLogException:
            return DefaultStrings.continueThisDayLogException
        case .hornMode:
            return DefaultStrings.hornMode
        case .garminConnectiqEnable:
            return DefaultStrings.garminConnectiqEnable
        case .garminConnectiqUseBeta:
            return DefaultStrings.garminConnectiqUseBeta
        case .mibandFixrsEnable:
            return DefaultStrings.mibandFixrsEnable
        case .lastMac:
            return DefaultStrings.lastMac
        case .useGps:
            return DefaultStrings.useGps
        case .useShortPwm:
            return DefaultStrings.useShortPwm
        case .alarmsEnabled:
            return DefaultStrings.alarmsEnabled
        case .disablePhoneVibrate:
            return DefaultStrings.disablePhoneVibrate
        case .disablePhoneBeep:
            return DefaultStrings.disablePhoneBeep
        case .useWheelBeepForAlarm:
            return DefaultStrings.useWheelBeepForAlarm
        case .alteredAlarms:
            return DefaultStrings.alteredAlarms
        case .alarm1Speed:
            return DefaultStrings.alarm1Speed
        case .alarm1Battery:
            return DefaultStrings.alarm1Battery
        case .alarm2Speed:
            return DefaultStrings.alarm2Speed
        case .alarm2Battery:
            return DefaultStrings.alarm2Battery
        case .alarm3Speed:
            return DefaultStrings.alarm3Speed
        case .alarm3Battery:
            return DefaultStrings.alarm3Battery
        case .alarmTemperature:
            return DefaultStrings.alarmTemperature
        case .rotationSpeed:
            return DefaultStrings.rotationSpeed
        case .rotationVoltage:
            return DefaultStrings.rotationVoltage
        case .rotationSet:
            return DefaultStrings.rotationSet
        case .powerFactor:
            return DefaultStrings.powerFactor
        case .alarmFactor1:
            return DefaultStrings.alarmFactor1
        case .alarmFactor2:
            return DefaultStrings.alarmFactor2
        case .alarmFactor3:
            return DefaultStrings.alarmFactor3
        case .warningSpeed:
            return DefaultStrings.warningSpeed
        case .warningPwm:
            return DefaultStrings.warningPwm
        case .warningSpeedPeriod:
            return DefaultStrings.warningSpeedPeriod
        case .alarmCurrent:
            return DefaultStrings.alarmCurrent
        case .alarmBattery:
            return DefaultStrings.alarmBattery
        case .ledEnabled:
            return DefaultStrings.ledEnabled
        case .drlEnabled:
            return DefaultStrings.drlEnabled
        case .taillightEnabled:
            return DefaultStrings.taillightEnabled
        case .handleButtonDisabled:
            return DefaultStrings.handleButtonDisabled
        case .speakerVolume:
            return DefaultStrings.speakerVolume
        case .beeperVolume:
            return DefaultStrings.beeperVolume
        case .pedalsAdjustment:
            return DefaultStrings.pedalsAdjustment
        case .pedalSensivity:
            return DefaultStrings.pedalSensivity
        case .lightMode:
            return DefaultStrings.lightMode
        case .strobeMode:
            return DefaultStrings.strobeMode
        case .ledMode:
            return DefaultStrings.ledMode
        case .pedalsMode:
            return DefaultStrings.pedalsMode
        case .rollAngle:
            return DefaultStrings.rollAngle
        case .rideMode:
            return DefaultStrings.rideMode
        case .lockMode:
            return DefaultStrings.lockMode
        case .transportMode:
            return DefaultStrings.transportMode
        case .goHomeMode:
            return DefaultStrings.goHomeMode
        case .fancierMode:
            return DefaultStrings.fancierMode
        case .alarmMode:
            return DefaultStrings.alarmMode
        case .wheelMaxSpeed:
            return DefaultStrings.wheelMaxSpeed
        case .wheelKsAlarm1:
            return DefaultStrings.wheelKsAlarm1
        case .wheelKsAlarm2:
            return DefaultStrings.wheelKsAlarm2
        case .wheelKsAlarm3:
            return DefaultStrings.wheelKsAlarm3
        case .ks18lScaler:
            return DefaultStrings.ks18lScaler
        case .useRatio:
            return DefaultStrings.useRatio
        case .gwInMiles:
            return DefaultStrings.gwInMiles
        case .gotwayVoltage:
            return DefaultStrings.gotwayVoltage
        case .gotwayNegative:
            return DefaultStrings.gotwayNegative
        case .hwPwm:
            return DefaultStrings.hwPwm
        case .connectBeep:
            return DefaultStrings.connectBeep
        case .lightEnabled:
            return DefaultStrings.lightEnabled
        case .profileName:
            return DefaultStrings.profileName
        case .batteryCapacity:
            return DefaultStrings.batteryCapacity
        case .chargingPower:
            return DefaultStrings.chargingPower
        case .iconConnection:
            return DefaultStrings.iconConnection
        case .iconLogging:
            return DefaultStrings.iconLogging
        case .iconWatch:
            return DefaultStrings.iconWatch
        }
    }
}
